# -*- coding: utf-8 -*-
"""21341015_ArnabSaha_A3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/171-YQ2aRA_WlQ85iQI29_wftSjEVjqCF

Student ID: 21341015
"""

import math

def score_of_uti(ge, goal):
    weights = [1, 0, 1, 5]
    N = max(len(ge), len(goal))
    score = 0
    for i in range(N):
        g = ord(ge[i]) if i < len(ge) else 0
        t = ord(goal[i]) if i < len(goal) else 0
        w = weights[i] if i < len(weights) else 1
        score -= w * abs(g - t)
    return score

def utility_score_boost(ge, goal, st):
    weights = [1, 0, 1, 5]
    booster_multiplier = 0.21
    N = max(len(ge), len(goal))
    score = 0
    for i in range(N):
        g = ord(ge[i]) if i < len(ge) else 0
        t = ord(goal[i]) if i < len(goal) else 0
        w = weights[i] if i < len(weights) else 1
        if i >= st:
            w *= booster_multiplier
        score -= w * abs(g - t)
    return score


def minimax(sequence, pool, goal, depth, alpha, beta, maximizing, special=False, s=None):
    if depth == 0 or not pool:
        if special and s is not None:
            return utility_score_boost(sequence, goal, s), sequence
        else:
            return score_of_uti(sequence, goal), sequence

    if maximizing:
        maxEval = -math.inf
        best_seq = ""
        for i, nuc in enumerate(pool):
            new_seq = sequence + nuc
            new_pool = pool[:i] + pool[i+1:]
            next_s_index = len(sequence) if (special and nuc == 'S') else s
            eval_score, _ = minimax(new_seq, new_pool, goal, depth - 1, alpha, beta, False, special, next_s_index)
            if eval_score > maxEval:
                maxEval = eval_score
                best_seq = new_seq
            alpha = max(alpha, eval_score)
            if beta <= alpha:
                break
        return maxEval, best_seq
    else:
        minEval = math.inf
        best_seq = ""
        for i, nuc in enumerate(pool):
            new_seq = sequence + nuc
            new_pool = pool[:i] + pool[i+1:]
            eval_score, _ = minimax(new_seq, new_pool, goal, depth - 1, alpha, beta, True, special, s)
            if eval_score < minEval:
                minEval = eval_score
                best_seq = new_seq
            beta = min(beta, eval_score)
            if beta <= alpha:
                break
        return minEval, best_seq

"""Task 1"""

def cal_1(p, g):
    score, gene = minimax("", p, g, len(p), -math.inf, math.inf, True)
    print("\nTask I Output:")
    print(f"Best gene sequence generated: {gene}")
    print(f"Utility score: {score}")

"""Task 2"""

def cal_2(p, g):
    pool_without_s = [n for n in p if n != 'S']
    score_normal, gene_normal = minimax("", pool_without_s, g, len(pool_without_s), -math.inf, math.inf, True)

    if 'S' in p:
        score_special, gene_special = minimax("", p, g, len(p), -math.inf, math.inf, True, special=True)
        decision = "YES" if score_special > score_normal else "NO"
        print("\nTask II Output:")
        print(decision)
        print("With special nucleotide")
        print(f"Best gene sequence generated: {gene_special}")
        print(f"Utility score: {round(score_special, 2)}")
    else:
        print("\nTask II Output:")
        print("NO")
        print("No special nucleotide 'S' in pool.")

"""input function"""

def ip():
    pool = input("Enter nucleotide pool: ").strip().split(',')
    target = input("Enter target gene sequence: ").strip()

    cal_1(pool.copy(), target)
    cal_2(pool.copy(), target)

if __name__ == "ip":
    ip()